### ISSUE TITLE
Upadate SpeciesType

### ISSUE THREAD

**Issue by owolp** [Team-Captain-Marvel-2016/TeamWorkSkeletonSample#11]
Update FootballPlayerAssembly -> Enumerators -> SpeciesType.cs with all planets once they have constructors.

**Comment by shakuu** [comment]
Only do that when a planet is fully implemented, otherwise it'll break randomization.
( random number is generated in range 0 - enumSize ) So it'll be looking for planets without factory constructors ( current logic can only search in Factory methods, not nested class's actual constructors )

**Comment by owolp** [comment]
Ok

**Comment by owolp** [comment]
Depends on #6
