### ISSUE TITLE
Implement Uranian

### ISSUE THREAD

**Issue by shakuu** [Team-Captain-Marvel-2016/TeamWorkSkeletonSample#5]
SpeciesNameGenerators -> GenerateName()
internal abstract class Uranian 
RolesClasses.UranianFootballPlayer : 
Attacker
Defender
Midfielder
Goalkeeper

**Comment by shakuu** [comment]
Fully implemented

**Comment by shakuu** [comment]
GenerateName() 

Dictionaries are empty.

**Comment by owolp** [comment]
Done
