### ISSUE TITLE
Implement IPass Interface

### ISSUE THREAD

**Issue by shakuu** [Team-Captain-Marvel-2016/TeamWorkSkeletonSample#7]
FootballPlayerAssembly -> FootballPlayerAbstractClass -> FootballPlayerPassImplementation.cs

**Comment by owolp** [comment]
Some additional info needed here which will be the same for the rest of the interfaces - IShoot, ITackle etc.

**Comment by shakuu** [comment]
It'll need some additional methods on top of the actual implementation.

**Comment by shakuu** [comment]
done
